### ISSUE TITLE
Sweep: ImportError: cannot import name 'AssistantManager' from partially initialized module 'assistant_manager' (most likely due to a circular import) (C:\smarthat\assistant_manager.py)

### ISSUE THREAD

**Issue by GravityPhone** [GravityPhone/SmarterHat#12]
Administrator in smarthat on  main [?] via 🐍 v3.9.0
❯ python .\main_controller.py
Traceback (most recent call last):
  File "C:\smarthat\main_controller.py", line 6, in <module>
    from assistant_manager import AssistantManager
  File "C:\smarthat\assistant_manager.py", line 4, in <module>
    from interactions import interact_with_assistant
  File "C:\smarthat\interactions.py", line 4, in <module>
    from assistant_manager import AssistantManager
ImportError: cannot import name 'AssistantManager' from partially initialized module 'assistant_manager' (most likely due to a circular import) (C:\smarthat\assistant_manager.py)

<details open>
<summary>Checklist</summary>

- [X] Modify `assistant_manager.py` ✓ https://github.com/GravityPhone/SmarterHat/commit/ec649b339a4491ea95a7bce4b29343279a8e06f9 [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/importerror_cannot_import_name_assistant/assistant_manager.py)
- [X] Running GitHub Actions for `assistant_manager.py` ✓  [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/importerror_cannot_import_name_assistant/assistant_manager.py)
- [X] Modify `interactions.py` ! No changes made  [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/importerror_cannot_import_name_assistant/interactions.py)
- [X] Running GitHub Actions for `interactions.py` ✗  [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/importerror_cannot_import_name_assistant/interactions.py)
</details>

**Comment by GravityPhone** [comment]
Sweep: python .\main_controller.py
Traceback (most recent call last):
File "C:\smarthat\main_controller.py", line 9, in
from interactions import interact_with_assistant
File "C:\smarthat\interactions.py", line 5, in
from eleven_labs_manager import eleven_labs_manager
ImportError: cannot import name 'eleven_labs_manager' from 'eleven_labs_manager' (C:\smarthat\eleven_labs_manager.py)
