### ISSUE TITLE
Sweep: Address python error

### ISSUE THREAD

**Issue by GravityPhone** [GravityPhone/SmarterHat#14]
python .\main_controller.py
Traceback (most recent call last):
File "C:\smarthat\main_controller.py", line 9, in
from interactions import interact_with_assistant
File "C:\smarthat\interactions.py", line 5, in
from eleven_labs_manager import eleven_labs_manager
ImportError: cannot import name 'eleven_labs_manager' from 'eleven_labs_manager' (C:\smarthat\eleven_labs_manager.py)

<details open>
<summary>Checklist</summary>

- [X] Modify `interactions.py` ✓ https://github.com/GravityPhone/SmarterHat/commit/45dafcebad47ab334eb86626ba60bdb01f4cd463 [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/address_python_error/interactions.py)
- [X] Running GitHub Actions for `interactions.py` ✓  [Edit](https://github.com/GravityPhone/SmarterHat/edit/sweep/address_python_error/interactions.py)
</details>

**Comment by GravityPhone** [comment]
Sweep: also ensure that main_controller.py is in line with all these updates.
